# DB connections
tcp:
  routers:
    mongodb:
      rule: "HostSNI(`mongodb.cypherix.io`)"
      entryPoints:
        - "mongo"
      tls:
        passthrough: true
      service: "mongodb"
  services:
    mongodb:
      loadBalancer:
        servers:
          - address: "192.168.1.251:27017"

# HTTP connections
http:
  routers:
    mongodb:
      rule: "Host(`mongodb.cypherix.io`)"
      service: "mongodb"
  services:
    mongodb:
      loadBalancer:
        servers:
          - url: "http://192.168.1.251:27017"