http:
  routers:
    bazarr:
      rule: "Host(`bazarr.cypherix.dev`)"
      service: "bazarr"
  services:
    bazarr:
      loadBalancer:
        servers:
          - url: "http://192.168.1.244:6767"