http:
  routers:
    portainer:
      rule: "Host(`portainer.cypherix.dev`)"
      service: "portainer"
  services:
    portainer:
      loadBalancer:
        servers:
          - url: "http://192.168.1.251:9000"