http:
  routers:
    tautulli:
      rule: "Host(`tautulli.cypherix.dev`)"
      service: "tautulli"
  services:
    tautulli:
      loadBalancer:
        servers:
          - url: "http://192.168.1.251:8181"