version: '3.5'

services:

# Indexers
#-------------------------------------------------------------
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    network_mode: service:openvpn
    depends_on:
      - openvpn
      - flaresolverr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=true
    volumes:
      - ${DOCKER_DIR}/jackett/config:/config
    ports:
      - '9117:9117'
#-------------------------------------------------------------
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    network_mode: service:openvpn
    depends_on:
      - openvpn
      - flaresolverr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DIR}/prowlarr/config:/config
    ports:
      - '9696:9696'


# Utilities
#-------------------------------------------------------------
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: service:openvpn
    depends_on:
      - openvpn
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - '8191:8191'


# VPN
#-------------------------------------------------------------
  openvpn:
    image: dperson/openvpn-client
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VPNPORT=${OPENVPN_PORT}
      - VPN_FILES=${OPENVPN_FILES}
      - FIREWALL=''
    volumes:
      # for openvpn to access TUN device
      - /dev/net:/dev/net:z
      - ${DOCKER_DIR}/openvpn/vpn:/vpn
