version: '3'

services:

  # MailDev
  maildev:
    image: maildev/maildev
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - '1080:1080'
      - '1025:1025'
    command: [
      "--web", "1080",
      "--smtp", "1025",
      "--outgoing-host", "${MAILDEV_OUTGOING_HOST}",
      "--outgoing-port", "${MAILDEV_OUTGOING_PORT}",
      "--outgoing-user", "${MAILDEV_OUTGOING_USER}",
      "--outgoing-pass", "${MAILDEV_OUTGOING_PASS}",
      "--outgoing-secure",
      "--auto-relay"
    ]
