version: '3.5'

services:

# Indexers
#-------------------------------------------------------------
  jackett:
    image: lscr.io/linuxserver/jackett
    depends_on:
      - flaresolverr
    networks:
      - vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=true
    volumes:
      - ${DOCKER_DIR}/jackett/config:/config
    ports:
      - target: 9117
        published: 9117
        protocol: tcp
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
#-------------------------------------------------------------
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    depends_on:
      - flaresolverr
    networks:
      - vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DIR}/prowlarr/config:/config
    ports:
      - target: 9696
        published: 9696
        protocol: tcp
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager


# Utilities
#-------------------------------------------------------------
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    networks:
      - vpn
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - target: 8191
        published: 8191
        protocol: tcp
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager


# Networks
#-------------------------------------------------------------
networks:
  vpn:
    external: true
    name: ${NETWORK_WIREGUARD_NAME}