version: "3.5"

services:
#-------------------------------------------------------------
  tautulli:
    image: tautulli/tautulli:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DIR}/tautulli/config:/config
    ports:
      - "8181:8181"
#-------------------------------------------------------------
  petio:
    image: ghcr.io/petio-team/petio:latest
    depends_on:
      - "petio-mongodb"
    networks:
      - "petio-network"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DIR}/petio/app/api/config:/app/api/config
      - ${DOCKER_DIR}/petio/app/logs:/app/logs
    ports:
      - "7777:7777"

  petio-mongodb:
    image: mongo:4.4
    networks:
      - "petio-network"
    volumes:
      - ${DOCKER_DIR}/petio/data/db:/data/db    
    ports:
      - "67017:27017"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
          - node.platform.os == linux
#-------------------------------------------------------------
networks:
  petio-network:
    driver: overlay
