version: '3.5'

services:

# Indexers
#-------------------------------------------------------------
  jackett:
    image: lscr.io/linuxserver/jackett
    depends_on:
      - flaresolverr
    networks:
      - vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=true
    volumes:
      - ${DOCKER_DIR}/jackett/config:/config
    ports:
      - 9117:9117
#-------------------------------------------------------------
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    depends_on:
      - flaresolverr
    networks:
      - vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DIR}/prowlarr/config:/config
    ports:
      - 9696:9696


# Utilities
#-------------------------------------------------------------
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    networks:
      - vpn
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - 8191:8191


# Networks
#-------------------------------------------------------------
networks:
  vpn:
    external: true
    name: ${VPN_NETWORK_NAME}