version: "3.5"

services:
  db:
    image: mongo:4.4.6
    volumes:
      - ${DOCKER_DIR}/mongodb/data/db:/data/db
      - ${DOCKER_DIR}/mongodb/data/configdb:/data/configdb
    ports:
      - "27017:27017"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
          - node.platform.os == linux