version: "3.5"

services:
  db:
    image: mongo:4.4.6
    volumes:
      - ${DOCKER_DIR}/mongodb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ${DOCKER_DIR}/mongodb/data/db:/data/db
      - ${DOCKER_DIR}/mongodb/data/configdb:/data/configdb
      # - ${DOCKER_DIR}/mongodb/etc/mongod.conf:/etc/mongod.conf
      - ${DOCKER_DIR}/_certs:/certs
    ports:
      - "27017-27019:27017-27019"
    command: [
      # "--config", "/etc/mongod.conf",
      "--tlsMode", "requireTLS",
      "--tlsAllowConnectionsWithoutCertificates", "requireTLS",
      "--tlsCertificateKeyFile", "/certs/origin/cypherix.io.pem",
      "--tlsCAFile", "/certs/origin_ca_rsa_root.pem",
    ]
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
          - node.platform.os == linux