version: '3.9'

services:
  portainer:
    image: portainer/portainer-ce:latest
    command: --admin-password-file /volume1/docker/portainer/secrets/pass
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/portainer/data:/data
    networks:
      - bridge
    deploy:
      restart_policy:
        condition: on-failure
networks:
  bridge:
    external: true
