version: '3'

services:
  traefik:
    image: traefik:latest
    ports:
      - '4080:80'
      - '40443:443'
      # web UI
      - '40880:8080'
    volumes:
      - /volume1/docker/traefik/etc:/etc
      - /volume1/docker/traefik/run:/run:ro
      - /volume1/docker/traefik/certs:/certs:ro
