version: '3'

services:
  traefik:
    image: traefik:v2.6
    ports:
      - '4080:80'
      - '40443:443'
      # web UI
      - '40880:8080'
    volumes:
      # docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      # mapped volumes
      - /volume1/docker/traefik/etc:/etc
      - /volume1/docker/traefik/run:/run:ro
      - /volume1/docker/traefik/certs:/certs:ro
