version: '3.5'

services:

# Indexers
#-------------------------------------------------------------
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: media-indexerr--jackett
    network_mode: service:openvpn
    depends_on:
      - openvpn
      - flaresolverr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=true
    volumes:
      - ${DOCKER_DIR}/jackett/config:/config
    restart: unless-stopped
#-------------------------------------------------------------
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: media-indexerr--prowlarr
    network_mode: service:openvpn
    depends_on:
      - openvpn
      - flaresolverr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DIR}/prowlarr/config:/config
    restart: unless-stopped


# Utilities
#-------------------------------------------------------------
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: media-indexerr--flaresolverr
    network_mode: service:openvpn
    depends_on:
      - openvpn
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    restart: unless-stopped


# VPN
#-------------------------------------------------------------
  openvpn:
    image: dperson/openvpn-client
    container_name: media-indexerr--openvpn
    cap_add:
      - NET_ADMIN
    networks:
      - vpn_bridge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VPNPORT=${OPENVPN_PORT}
      - VPN_FILES=${OPENVPN_FILES}
      # - FIREWALL=''
    volumes:      
      - /dev/net:/dev/net:z # for openvpn to access TUN device
      - ${DOCKER_DIR}/openvpn/vpn:/vpn
    restart: unless-stopped


# Networks
#-------------------------------------------------------------
networks:
  vpn_bridge:
    driver: bridge