version: '3.5'

services:

# Indexers
#-------------------------------------------------------------
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    networks:
      - vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DIR}/prowlarr/config:/config
    ports:
      - '9696:9696'
    restart: unless-stopped


# Networks
#-------------------------------------------------------------
networks:
  vpn:
    external: true
    name: ${NETWORK_WIREGUARD_NAME}