version: '3.5'

services:

# Downloaders
#-------------------------------------------------------------
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    networks:
      - vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=1337
    volumes:
      - ${DOCKER_DIR}/qbittorrent/config:/config
      - ${DOCKER_DIR}/qbittorrent/webui:/etc/webui
      - ${DOWNLOADS_SEEDING_DIR}:/downloads/seeding
      - ${DOWNLOADS_MANUAL_DIR}:/downloads/manual
      - ${DOWNLOADS_GAMES_DIR}:/downloads/games
    ports:
      - "1337:1337"
      - "13377:13377"
      - "13377:13377/udp"
    restart: unless-stopped

# Indexers
#-------------------------------------------------------------
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    networks:
      - vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DIR}/prowlarr/config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped


# Networks
#-------------------------------------------------------------
networks:
  vpn:
    external: true
    name: ${NETWORK_WIREGUARD_NAME}